// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  matchId: __t.u64().primaryKey().name("match_id"),
  state: __t.string(),
  maxSlots: __t.u8().name("max_slots"),
  tickCount: __t.u64().name("tick_count"),
  createdAt: __t.timestamp().name("created_at"),
  startedAt: __t.option(__t.timestamp()).name("started_at"),
  finishedAt: __t.option(__t.timestamp()).name("finished_at"),
  winnerPlayerId: __t.option(__t.u64()).name("winner_player_id"),
});
