// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  obstacleId: __t.u64().primaryKey().name("obstacle_id"),
  matchId: __t.u64().name("match_id"),
  lane: __t.i8(),
  distance: __t.f32(),
  active: __t.bool(),
  spawnedAtTick: __t.u64().name("spawned_at_tick"),
});
