// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  playerId: __t.u64().primaryKey().name("player_id"),
  matchId: __t.u64().name("match_id"),
  x: __t.f32(),
  distance: __t.f32(),
  speed: __t.f32(),
  steering: __t.f32(),
  throttle: __t.f32(),
  boost: __t.bool(),
  inputSeq: __t.u32().name("input_seq"),
});
