// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CollisionEvent = __t.object("CollisionEvent", {
  playerId: __t.u64(),
  obstacleId: __t.u64(),
  strikesRemaining: __t.u8(),
  createdAt: __t.timestamp(),
});
export type CollisionEvent = __Infer<typeof CollisionEvent>;

export const GameTickSchedule = __t.object("GameTickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  matchId: __t.u64(),
});
export type GameTickSchedule = __Infer<typeof GameTickSchedule>;

export const Match = __t.object("Match", {
  matchId: __t.u64(),
  state: __t.string(),
  maxSlots: __t.u8(),
  tickCount: __t.u64(),
  createdAt: __t.timestamp(),
  startedAt: __t.option(__t.timestamp()),
  finishedAt: __t.option(__t.timestamp()),
  winnerPlayerId: __t.option(__t.u64()),
});
export type Match = __Infer<typeof Match>;

export const Obstacle = __t.object("Obstacle", {
  obstacleId: __t.u64(),
  matchId: __t.u64(),
  x: __t.f32(),
  distance: __t.f32(),
  active: __t.bool(),
  spawnedAtTick: __t.u64(),
});
export type Obstacle = __Infer<typeof Obstacle>;

export const PlayerContact = __t.object("PlayerContact", {
  playerId: __t.u64(),
  email: __t.string(),
  consentGiven: __t.bool(),
  consentedAt: __t.timestamp(),
});
export type PlayerContact = __Infer<typeof PlayerContact>;

export const PlayerPosition = __t.object("PlayerPosition", {
  playerId: __t.u64(),
  matchId: __t.u64(),
  x: __t.f32(),
  distance: __t.f32(),
  speed: __t.f32(),
  steering: __t.f32(),
  throttle: __t.f32(),
  boost: __t.bool(),
  inputSeq: __t.u32(),
});
export type PlayerPosition = __Infer<typeof PlayerPosition>;

export const PlayerProfile = __t.object("PlayerProfile", {
  playerId: __t.u64(),
  matchId: __t.u64(),
  identity: __t.option(__t.identity()),
  name: __t.string(),
  vehicleType: __t.string(),
  isBot: __t.bool(),
  joinedAt: __t.timestamp(),
});
export type PlayerProfile = __Infer<typeof PlayerProfile>;

export const PlayerVitals = __t.object("PlayerVitals", {
  playerId: __t.u64(),
  matchId: __t.u64(),
  strikesRemaining: __t.u8(),
  score: __t.u32(),
  eliminated: __t.bool(),
  rank: __t.option(__t.u8()),
});
export type PlayerVitals = __Infer<typeof PlayerVitals>;

