// Project Graveyard — client.
// module_bindings/ is generated by:
//   spacetime generate --lang typescript --out-dir client/src/module_bindings --module-path server
import { DbConnection, tables } from './module_bindings/index.ts';

// ---- CONFIG ----
// Local defaults; Vercel sets VITE_SPACETIME_* at build time.
const MODULE = import.meta.env.VITE_SPACETIME_MODULE || 'project-graveyard-local';
const URI    = import.meta.env.VITE_SPACETIME_URI    || 'ws://localhost:3000';
// ----------------------------------------------------

const tombstones = new Map();
const wallEl   = document.getElementById('wall');
const countEl  = document.getElementById('count');
const statusEl = document.getElementById('status');
const navEl    = document.getElementById('nav');

if (location.hash === '#screen') document.body.classList.add('screen');

const enterScreen = (e) => {
  e?.preventDefault();
  location.hash = 'screen';
  location.reload();
};
document.getElementById('screen-link')?.addEventListener('click', enterScreen);
document.getElementById('screen-link-footer')?.addEventListener('click', enterScreen);

window.addEventListener('scroll', () => {
  navEl?.classList.toggle('scrolled', window.scrollY > 8);
}, { passive: true });

const esc = s => (s || '').replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));

function render() {
  const list = [...tombstones.values()].sort((a, b) => Number(b.id - a.id));
  countEl.textContent = list.length;
  if (!list.length) {
    wallEl.innerHTML = `<div class="wall-empty">The ground is still empty. Be the first to bury something.</div>`;
    return;
  }
  wallEl.innerHTML = list.map(t => `
    <article class="grave">
      <div class="rip">R · I · P</div>
      <div class="name">${esc(t.name)}</div>
      ${t.cause ? `<div class="cause">${esc(t.cause)}</div>` : ''}
      ${t.epitaph ? `<div class="epitaph">“${esc(t.epitaph)}”</div>` : ''}
      ${t.buriedBy ? `<div class="by">— ${esc(t.buriedBy)}</div>` : ''}
    </article>`).join('');
}

const conn = DbConnection.builder()
  .withUri(URI)
  .withDatabaseName(MODULE)
  .onConnect((c) => {
    statusEl.textContent = 'Live';
    c.subscriptionBuilder().subscribe(tables.tombstone);
  })
  .onConnectError((_c, err) => { statusEl.textContent = 'Offline'; console.error(err); })
  .onDisconnect(() => { statusEl.textContent = 'Reconnecting…'; })
  .build();

conn.db.tombstone.onInsert((_ctx, row) => { tombstones.set(row.id, row); render(); });
conn.db.tombstone.onDelete((_ctx, row) => { tombstones.delete(row.id); render(); });

const nameEl = document.getElementById('name');
const causeEl = document.getElementById('cause');
const epEl = document.getElementById('epitaph');
const byEl = document.getElementById('by');
document.getElementById('bury-form').addEventListener('submit', (e) => {
  e.preventDefault();
  if (!nameEl.value.trim()) { nameEl.focus(); return; }
  conn.reducers.bury({
    name: nameEl.value,
    cause: causeEl.value,
    epitaph: epEl.value,
    buriedBy: byEl.value,
  });
  nameEl.value = causeEl.value = epEl.value = '';
  nameEl.focus();
});
