// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  attackerPlayerId: __t.u64().name("attacker_player_id"),
  targetPlayerId: __t.u64().name("target_player_id"),
  attackKind: __t.string().name("attack_kind"),
  strikesRemaining: __t.u8().name("strikes_remaining"),
  createdAt: __t.timestamp().name("created_at"),
});
