// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  playerId: __t.u64().primaryKey().name("player_id"),
  matchId: __t.u64().name("match_id"),
  identity: __t.option(__t.identity()),
  name: __t.string(),
  vehicleType: __t.string().name("vehicle_type"),
  isBot: __t.bool().name("is_bot"),
  joinedAt: __t.timestamp().name("joined_at"),
});
